"""empty message

Revision ID: 9a1553454acc
Revises: c8b61db996a7
Create Date: 2023-01-18 02:32:18.475932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1553454acc'
down_revision = 'c8b61db996a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos',sa.Column('completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos','completed')

    # ### end Alembic commands ###
